### ISSUE TITLE
Can't join server when using PacketEventsAPI plugin

### ISSUE THREAD

**Issue by TheJoshue** [XenonCommunity/XenonCord#6]
### XenonCord version

0.0.84

### Server version

git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:b67418a:unknown by realstresser

### Client version

1.21

### XenonCord plugins

Plugins (30): AlwaysOnline, AuthMeBungee, BungeeControl-Red, BungeeGuard, BungeeUtils, ClientDetector, CustomF3Brand, DiscordOTP, DiscordUC, Geyser-BungeeCord, InteractiveBoard, LuckPerms, MyCommand for BungeeCord, NuVotifier, PAPIProxyBridge, Pl-Hide-Pro, Protocolize, ProtocolizeLegacySupport, Reconnect, SCAutoBroadcaster, ServerUtils, SkinsRestorer, SlingShot, SyncCommands, VulcanBungee, WickedMaintenance, ajQueue, floodgate, packetevents and spark

### The bug

I simply try to join the server

I want to mention that this issue does not happen on regular Waterfall

![image](https://github.com/user-attachments/assets/63a98361-3d4a-41e6-a08d-769444a19ccd)

### Log output (links)

https://mclo.gs/GZzHuy2

### Checking

- [X] This problem is related to XenonCord! not plugins!
- [X] This is a **issue**.
- [X] I did not use this form to request a feature.

**Comment by RealSuperUser** [comment]
Confirmed this issue. working on a fix.

**Comment by RealSuperUser** [comment]
This issue is no longer persists
