### ISSUE TITLE
PlHidePro plugin won't load because LuckPerms does not load before it for some weird reason

### ISSUE THREAD

**Issue by TheJoshue** [XenonCommunity/XenonCord#7]
### XenonCord version

0.0.84

### Server version

git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:b67418a:unknown by realstresser

### Client version

1.21

### XenonCord plugins

Plugins (30): AlwaysOnline, AuthMeBungee, BungeeControl-Red, BungeeGuard, BungeeUtils, ClientDetector, CustomF3Brand, DiscordOTP, DiscordUC, Geyser-BungeeCord, InteractiveBoard, LuckPerms, MyCommand for BungeeCord, NuVotifier, PAPIProxyBridge, Pl-Hide-Pro, Protocolize, ProtocolizeLegacySupport, Reconnect, SCAutoBroadcaster, ServerUtils, SkinsRestorer, SlingShot, SyncCommands, VulcanBungee, WickedMaintenance, ajQueue, floodgate, packetevents and spark

### The bug

Even though i made sure that bungee.yml file inside of PlHidePro plugin has "depends: [LuckPerms]", this still is the issue.

### Log output (links)

https://mclo.gs/BaT31aY

### Checking

- [X] This problem is related to XenonCord! not plugins!
- [X] This is a **issue**.
- [X] I did not use this form to request a feature.

**Comment by RealSuperUser** [comment]
Because Xenon Cord's plugin loader loads plugins in different threads instead of one it causes this issue.
not sure what to do but I'll try to add a system to actually load those plugins with depend tag first.

**Comment by RealSuperUser** [comment]
Pls try to load those plugins and share results here.

**Comment by TheJoshue** [comment]
Sorry for delay
Tested, everything works perfectly
Keep up good work
I will see when i have more time to suggest more things because there is really a lot of that could be implemented, etc

Do you have Discord support server or what is your discord? @RealSuperUser

**Comment by RealSuperUser** [comment]
> Sorry for delay Tested, everything works perfectly Keep up good work I will see when i have more time to suggest more things because there is really a lot of that could be implemented, etc
Thanks for reporting those bugs.
> Do you have Discord support server or what is your discord? @RealSuperUser
I lost my access to that account, my new account is @BuffOvrFlw. https://discord.gg/CSb4KWUx this is discord server as well
